### PR TITLE
report on migration progress

### PR DESCRIPTION
**Pull request by jtulley**
note when a migration is started and finished, to more easily
see that progress is being made.

### CODE REVIEW

**Comment by jargv** [comment]
Hey Jeff! I saw the request but not the PR, so I added logging support in a branch (logging). Let me know if it does what you're looking for.

**Comment by jargv** [comment]
Here's the details about that branch:
https://github.com/jargv/mig/tree/logging#logging

**Comment by jtulley** [comment]
The logging branch looks good.  Could you get that and the other PR with "CREATE TABLE IF EXISTS" commited, then I could retry my deadlock case.

**Comment by jargv** [comment]
Fixed by #4

**Pull request closed without merging**
